file.directory:
  profile: /Users/shimhyunwoo/workspace/study/spring/my-project/src/main/resources/static/profile/
  contents: /Users/shimhyunwoo/workspace/study/spring/my-project/src/main/resources/static/posts/
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/workspace/h2/shop
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: ture
        format_sql: true
        default_batch_fetch_size: 20
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace

server.servlet.session:
  tracking-modes: cookie
  timeout: 3600
