file:
  directory:

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/workspace/h2/shop
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: ture
        format_sql: true
        default_batch_fetch_size: 20
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    redis:
      host: localhost
      port: 6379

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace

server.servlet.session:
  tracking-modes: cookie
  timeout: 3600
